# doit forget plot_benchmark_forward_time0.01_RajagopalLaiUhlrich2023
# doit forget plot_benchmark_forward_time0.1_RajagopalLaiUhlrich2023
# doit forget plot_benchmark_forward_time1.0_RajagopalLaiUhlrich2023
# doit forget plot_benchmark_manager_time0.01_RajagopalLaiUhlrich2023
# doit forget plot_benchmark_manager_time0.1_RajagopalLaiUhlrich2023
# doit forget plot_benchmark_manager_time1.0_RajagopalLaiUhlrich2023
# doit forget plot_benchmark_realize_RajagopalLaiUhlrich2023
doit forget plot_perf_forward_time0.001_RajagopalLaiUhlrich2023
doit forget plot_perf_forward_time0.005_RajagopalLaiUhlrich2023
doit forget plot_perf_forward_time0.01_RajagopalLaiUhlrich2023
doit forget plot_perf_forward_time0.05_RajagopalLaiUhlrich2023
doit forget plot_perf_forward_time0.1_RajagopalLaiUhlrich2023
doit forget plot_perf_forward_time0.5_RajagopalLaiUhlrich2023
doit forget plot_perf_forward_time1.0_RajagopalLaiUhlrich2023
doit forget plot_perf_forward_time10.0_RajagopalLaiUhlrich2023
doit forget plot_perf_forward_time5.0_RajagopalLaiUhlrich2023