doit forget plot_benchmark_forward_time0.01_RajagopalLaiUhlrich2023
doit forget plot_benchmark_forward_time0.1_RajagopalLaiUhlrich2023
doit forget plot_benchmark_forward_time1.0_RajagopalLaiUhlrich2023
doit forget plot_benchmark_manager_time0.01_RajagopalLaiUhlrich2023
doit forget plot_benchmark_manager_time0.1_RajagopalLaiUhlrich2023
doit forget plot_benchmark_manager_time1.0_RajagopalLaiUhlrich2023
